### ISSUE TITLE
AoT compliation error on express

### ISSUE THREAD

**Issue by chriseugenerodriguez** [ngx-universal/state-transfer#12]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

production script command using express, running angular universal with ngx-translate. Getting problem with the following error.

 ```
H:\d\node_modules\@ngx-translate\core\index.js:1
(function (exports, require, module, __filename, __dirname) { import { NgModule
} from "@angular/core";
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (H:\d\dist\ngfactory\src\app\app.server.module.ngfacto
ry.ts:18:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! d@0.0.0 build: `ts-node src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the d@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ChrisR\AppData\Roaming\npm-cache\_logs\2017-06-26T22_44_26
_359Z-debug.log
```

**Expected/desired behavior**

running server side render usng angular cli with ngx-translate and angular universal.

**Minimal reproduction of the problem with instructions**
basically this is my code, I just added the following.
https://stackoverflow.com/questions/44679189/angular-4-with-universal-ng2-translate

**app.server.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { ServerModule } from '@angular/platform-server';
**import { ServerStateTransferModule, StateTransferService  } from '@ngx-universal/state-transfer';**

import { AppModule } from './app.module';
import { AppComponent } from './app.component';

// TRANSLATE
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import {TranslateModule, TranslateLoader, TranslateService } from '@ngx-translate/core';
import { TranslateUniversalLoader } from './core/services/translate.service';



@NgModule({
    imports: [
        // UNIVERSAL
        BrowserModule.withServerTransition({appId: 'd'}),
        
        **ServerStateTransferModule.forRoot(),**
        ServerModule,
        AppModule,

        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useClass: TranslateUniversalLoader
            }
        }),
    ],
    bootstrap: [AppComponent]
})

export class AppServerModule {
    **constructor(private readonly stateTransfer: StateTransferService){}**
    
    **ngOnBootstrap = () => {
        this.stateTransfer.inject();
    }**
}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4

* **Browser:** [all ]

 
* **Language:** [TypeScript 2]

* **Node (for AoT issues):** `node --version` =  7.1

**Comment by fulls1z3** [comment]
@premiumwd have you ever tried [ngx-universal/translate-loader](https://github.com/ngx-universal/translate-loader)?

and which version of `ngx-translate` we're talking about? 6, or 7?

**Comment by chriseugenerodriguez** [comment]
@fulls1z3 I have tried but failed, I think its related to my server.ts file. The main issue is with express. There is not documentation on setup with express or the right express layout sample. Whats the difference between your state-loader, and translate-loader?

**Comment by fulls1z3** [comment]
@premiumwd I also saw your issue at stackoverflow. I'll try to have a look on it, and I'll try to help on that too if I can figure out something. Meanwhile, if we're talking about `ngx-translate` version 6, it runs at [ng-seed/universal](https://github.com/ng-seed/universal).

I hope it will help, otherwise let me know and let's see what we can do dude.

**Comment by chriseugenerodriguez** [comment]
@fulls1z3 thanks for the assitance friend. I managed to use [ngx-universal/translate-loader](https://github.com/ngx-universal/translate-loader) in project so I dont need to have a server.module.ts and app.module.ts to seperate logic for ngx-translate. I am getting a different error now.

```
ERROR in ./~/@ngx-universal/translate-loader/src/universal.translate-loader.js
Module not found: Error: Can't resolve '@ngx-cache/core' in 'H:\d\node_modules\@
ngx-universal\translate-loader\src'
 @ ./~/@ngx-universal/translate-loader/src/universal.translate-loader.js 5:0-51
 @ ./~/@ngx-universal/translate-loader/index.js
 @ ./src/app/app.module.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! d@0.0.0 prebuild: `ng build --prod --no-sourcemap && ngc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the d@0.0.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.
```

**package.json**
```
    "@ngx-translate/core": "^7.0.0",
    "@ngx-translate/http-loader": "^0.1.0",
    "@ngx-universal/translate-loader": "^0.4.0-beta.1",
```
**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { Inject, NgModule, PLATFORM_ID } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule, Http } from '@angular/http';

// TRANSLATE
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { UniversalTranslateLoader } from '@ngx-universal/translate-loader';

export function translateFactory(platformId: any, http: Http): TranslateLoader {
  const browserLoader = new TranslateHttpLoader(http);

  return new UniversalTranslateLoader(platformId, browserLoader, './assets/locales');
}

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

// PAGES
import { HomeModule, NotFoundModule, TestModule } from './layout/pages/index'

// SHARED
import { HeaderModule, FooterModule } from './layout/shared/index';

@NgModule({
  imports: [
    // UNIVERSAL
    BrowserModule.withServerTransition({appId: 'd'}),

    HttpModule,
    AppRoutingModule,

    // TRANSLATE
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (translateFactory),
        deps: [PLATFORM_ID, Http]
      }
    }),
    
    // PAGES
    HomeModule,
    TestModule,
    NotFoundModule,

    // TEMPLATE
    HeaderModule,
    FooterModule
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})

export class AppModule {
  constructor(@Inject(PLATFORM_ID) private readonly platformId: any) {}
}
```
**server.ts**
```
// the polyfills must be one of the first things imported in node.js.
// The only modules to be imported higher - node modules with es6-promise 3.x or other Promise polyfill dependency
// (rule of thumb: do it if you have zone.js exception that it has been overwritten)
// if you are including modules that modify Promise, such as NewRelic,, you must include them before polyfills
import 'angular2-universal-polyfills';
import 'ts-helpers';
import * as fs from 'fs';
import * as bodyParser from 'body-parser';
import * as cookieParser from 'cookie-parser';
import * as morgan from 'morgan';
import * as compression from 'compression';

// Angular 2 Universal
import { createEngine } from 'angular2-express-engine';

import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { platformServer, renderModuleFactory } from '@angular/platform-server';
import { enableProdMode } from '@angular/core';
import { AppServerModuleNgFactory } from './dist/ngfactory/src/app/app.server.module.ngfactory';
import * as express from 'express';
import { readFileSync } from 'fs';
import * as path from 'path';
import { join } from 'path';

// Routes
import { routes } from './server.routes';

const PORT = 4000;
const app = express();
const ROOT = path.join(path.resolve(__dirname, '..'));

enableProdMode();

app.use(cookieParser('Angular 2 Universal'));
app.use(bodyParser.json());
app.use(compression());

const accessLogStream = fs.createWriteStream(ROOT + '/morgan.log', {flags: 'a'})

app.use(morgan('common', {
  skip: (req, res) => res.statusCode < 400,
  stream: accessLogStream
}));

function cacheControl(req, res, next) {
  // instruct browser to revalidate in 60 seconds
  res.header('Cache-Control', 'max-age=60');
  next();
}
// Serve static files
app.use('/assets', cacheControl, express.static(path.join(__dirname, 'assets'), {maxAge: 30}));
app.use(cacheControl, express.static(path.join(ROOT, 'dist/client'), {index: false}));


/**
 * use universal for specific routes
 */
app.get('/');
routes.forEach(route => {
  app.get('/${route}');
  app.get('/${route}/*');
});

const template = readFileSync(join(__dirname, 'dist', 'index.html')).toString();

app.engine('html', (_, options, callback) => {
  const opts = { document: template, url: options.req.url };

  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});

app.set('view engine', 'html');
app.set('views', 'src')

app.get('*.*', express.static(join(__dirname, 'dist')));

app.get('*', (req, res) => {
  res.render('index', { req });
});

app.listen(PORT, () => {
  console.log(`listening on http://localhost:${PORT}!`);
});
```
**server.routes.ts**
```
let fs = require('fs');
let data: any = JSON.parse(fs.readFileSync('src/assets/locales.json', 'utf8'));

export const routes: string[] = data.locales;
```

**Comment by Shiroh1ge** [comment]
I see this is closed, but have you found a fix for your problem? I am getting the same error.
