### ISSUE TITLE
cannot read property '0' of undefined

### ISSUE THREAD

**Issue by fulls1z3** [ngx-universal/state-transfer#2]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**
Stack trace:
```
TypeError: Cannot read property '0' of undefined
    at ServerTransferState.inject (D:\@nglibs\universal-example-app\.server\server.js:39729:55)
    at AppServerModule.ngOnBootstrap (D:\@nglibs\universal-example-app\.server\server.js:50088:33)
    at SafeSubscriber._next (D:\@nglibs\universal-example-app\.server\server.js:87220:9)
    at SafeSubscriber.__tryOrUnsub (D:\@nglibs\universal-example-app\.server\server.js:480:16)
    at SafeSubscriber.next (D:\@nglibs\universal-example-app\.server\server.js:429:22)
    at Subscriber._next (D:\@nglibs\universal-example-app\.server\server.js:371:26)
    at Subscriber.next (D:\@nglibs\universal-example-app\.server\server.js:335:18)
    at FirstSubscriber._emitFinal (D:\@nglibs\universal-example-app\.server\server.js:33183:25)
    at FirstSubscriber._emit (D:\@nglibs\universal-example-app\.server\server.js:33166:14)
    at FirstSubscriber._next (D:\@nglibs\universal-example-app\.server\server.js:33145:18)
    at FirstSubscriber.Subscriber.next (D:\@nglibs\universal-example-app\.server\server.js:335:18)
    at FilterSubscriber._next (D:\@nglibs\universal-example-app\.server\server.js:24785:30)
    at FilterSubscriber.Subscriber.next (D:\@nglibs\universal-example-app\.server\server.js:335:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (D:\@nglibs\universal-example-app\.server\server.js:531:26)
    at InnerSubscriber._next (D:\@nglibs\universal-example-app\.server\server.js:107585:21)
```

**Expected/desired behavior**
It should not happen

**Minimal reproduction of the problem with instructions**
Build the server using @nglibs/universal-transfer-state, start node and just after initial navigation (on also when any page is navigated) voila!

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by IPRIT** [comment]
Any updates?

**Comment by fulls1z3** [comment]
Hi @IPRIT, looks like you've done it 👍
